// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include "C:/Graphics Libraries/Binaries/InsightApplications-3.20.0/ImageViewer/ImageViewerGUI.h"

Fl_Double_Window *tkMain=(Fl_Double_Window *)0;

GLSliceView<float, unsigned char> *tkWin=(GLSliceView<float, unsigned char> *)0;

Fl_Double_Window* make_window() {
  { tkMain = new Fl_Double_Window(520, 520, "SimpleImageViewer");
    { tkWin = new GLSliceView<float, unsigned char>(5, 5, 512, 512, "label");
      tkWin->box(FL_ENGRAVED_FRAME);
      tkWin->color((Fl_Color)FL_BACKGROUND_COLOR);
      tkWin->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      tkWin->labeltype(FL_NORMAL_LABEL);
      tkWin->labelfont(0);
      tkWin->labelsize(14);
      tkWin->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      tkWin->align(FL_ALIGN_CENTER);
      tkWin->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(tkWin);
    } // GLSliceView<float, unsigned char>* tkWin
    tkMain->end();
  } // Fl_Double_Window* tkMain
  return tkMain;
}
